#
# SPDX-FileCopyrightText: Copyright 2025 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#
name: Build ML SDK

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/arm/ml-sdk-linux-amd64:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    env:
      MANIFEST_URL: https://github.com/arm/ai-ml-sdk-manifest.git
      REPO_DIR: ${{ github.workspace }}/sdk

    steps:
      - name: Clone repositories and build
        run: |
          mkdir -p $REPO_DIR && cd $REPO_DIR

          # Initialize the default manifest state
          repo init -u $MANIFEST_URL
          repo sync --no-clone-bundle -j $(nproc)

          echo "Build VGF-Lib"
          # ./sw/vgf-lib/scripts/build.py -j $(nproc) --doc --test

          echo "Build Model Converter"
          # ./sw/model-converter/scripts/build.py -j $(nproc) --doc --test

          echo "Build Emulation Layer"
          export VK_LAYER_PATH=${{ github.workspace }}/install/share/vulkan/explicit_layer.d
          export LD_LIBRARY_PATH=${{ github.workspace }}/install/lib
          ./sw/emulation-layer/scripts/build.py -j $(nproc) --doc --test --install ${{ github.workspace }}/install

          echo "Build Scenario Runner"
          export VK_INSTANCE_LAYERS=VK_LAYER_ML_Graph_Emulation:VK_LAYER_ML_Tensor_Emulation
          ./sw/scenario-runner/scripts/build.py -j $(nproc) --doc --test

          echo "Build SDK Root"
          ./scripts/build.py -j $(nproc) --doc
