#
# SPDX-FileCopyrightText: Copyright 2025 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#
name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      MANIFEST_URL: https://github.com/arm/ai-ml-sdk-manifest.git
      REPO_DIR: sdk

    steps:
      - name: Run build in container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/arm/ml-sdk-linux-amd64:latest
          options: -v ${{ github.workspace }}:/src -w /src
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          run: |
            mkdir -p $REPO_DIR && cd $REPO_DIR

            # Initialize the default manifest state
            repo init -u $MANIFEST_URL
            repo sync --no-clone-bundle -j $(nproc)

      - name: Build VGF-Lib
        working-directory: $REPO_DIR/sw/vgf-lib
        run: ./scripts/build.py -j $(nproc)

      - name: Build Model Converter
        working-directory: $REPO_DIR/sw/model-converter
        run: ./scripts/build.py -j $(nproc)

      - name: Build Emulation Layer
        working-directory: $REPO_DIR/sw/emulation-layer
        run: ./scripts/build.py -j $(nproc)

      - name: Build Scenario Runner
        working-directory: $REPO_DIR/sw/scenario-runner
        run: ./scripts/build.py -j $(nproc)

      - name: Build SDK Root
        working-directory: $REPO_DIR
        run: ./scripts/build.py -j $(nproc) --doc
